server:
  port: 9090

spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/zdb?useSSL=false
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    initialization-mode: always
#    sql-script-encoding: utf-8
#  database:
#    username: sayeedhasan
#    password: secret
  jpa:
    hibernate:
      ddl-auto: update

app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/zdb
    username: root
    password: secret
    maximum-pool-size: 30